site_name: Reahill's Personal Site
site_description: Reahill的大脑外置。
site_author: Reahill
site_url: https://reahill.github.io
repo_url: https://github.com/reahill/reahill.github.io
theme:
  name: material
  features:
    - navigation.instant.fetch  # 启用即时导航预取
    - navigation.instant.sections  # 启用即时导航分区
    - navigation.instant.progress  # 启用即时导航进度条
    - navigation.tracking  # 启用导航跟踪
    - navigation.sidebar  # 启用侧边栏导航
    - navigation.tabs # 启用标签导航
    - navigation.tabs.sticky  # 启用粘性标签导航
    - navigation.top        # 启用返回顶部按钮
    - navigation.sections    # 启用页面内导航分区
    - navigation.expand      # 启用导航展开
    - navigation.paths      # 启用导航路径
    - navigation.indexes  # 启用索引导航
    - navigation.smooth_scroll  # 启用平滑滚动
    - search.highlight        # 启用搜索高亮
    - search.suggest          # 启用搜索建议
    - toc.follow            # 启用跟随目录
    - content.code.highlight  # 启用代码高亮
    - content.code.annotate   # 启用代码注释
    - content.code.copy      # 启用代码复制按钮
    - content.tabs            # 启用内容标签
  palette:
    # 1. 自动模式入口 - 不定义具体颜色，仅提供切换入口
    - media: "(prefers-color-scheme)"  # 匹配系统是否有主题偏好
      toggle: 
        icon: material/brightness-auto  # 自动模式图标
        name: 切换到浅色模式  # 当处于自动模式时，按钮显示此文字

    # 2. 浅色模式的具体配色
    - media: "(prefers-color-scheme: light)"  # 匹配系统浅色模式
      scheme: default                  # 使用浅色基础方案
      primary: black                   # 主色调：黑色
      accent: blue               # 强调色：蓝色
      toggle:
        icon: material/weather-sunny    # 太阳图标
        name: 切换到深色模式           # 在浅色模式下，按钮提示切换至深色

    # 3. 深色模式的具体配色
    - media: "(prefers-color-scheme: dark)"
      scheme: slate                    # 使用深色基础方案
      primary: black             # 主色调：黑色
      accent: indigo                    # 深色模式下，强调色可微调为更亮的蓝色
      toggle:
        icon: material/weather-night    # 月亮图标
        name: 切换到系统自动模式       # 在深色模式下，按钮提示切换回自动
  
  font:
    false  # 禁用自定义字体，使用系统默认字体
  
  language: zh                # 网站语言设置为中文
  
  icon:
    repo: fontawesome/brands/github  # 使用 FontAwesome 的 GitHub 图标
    logo: material/robot-confused-outline  # 网站 Logo 图标
    menu: material/menu  # 菜单图标
    close: material/close  # 关闭图标
    top: material/chevron-up  # 返回顶部图标

extra_css:
  - stylesheets/fonts.css
  - stylesheets/mathjax.css
  - stylesheets/quest-panel.css
  - stylesheets/download-btn.css
  - stylesheets/smooth-scroll.css  # 自定义字体样式文件

extra_javascript:
  - javascripts/mathjax-config.html
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:  
  - material.extensions.preview:  
      configurations:  
        - targets:
            include:  
              - changelog/index.md
              - customization.md  
              - insiders/changelog/*  
              - setup/extensions/*  
  - admonition
  - tables
  - attr_list
  - def_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true


plugins:
  - search  
  - blog

nav:
  - 首页: 
    - index.md
    - 观前提示: preview.md
    - 数学公式测试: test_math.md
  - 数学: 
    - math/index.md
    - 线性代数: math/linear_algebra/linear_algebra.md
    - 微积分（甲）Ⅰ: math/calculus_1/calculus_1.md
    - 微积分（甲）Ⅱ: math/calculus_2/calculus_2.md
  - 编程:
    - programming/index.md
    - C程序基础与设计: programming/C_language/C_language.md
  - 物理: physics/index.md
  - 工程基础: engineering_basics/index.md
  - 电路与电子: circuits_and_electronics/index.md
  - 控制与系统: control_and_systems/index.md
  - 信号与信息处理: signal_and_information_processing/index.md
  - 电力与电气: power_and_electrical/index.md
  - 人工智能与智能系统: ai_and_intelligent_systems/index.md
  - 实践与实训: practice_and_training/index.md

docs_dir: docs