site_name: Reahill's Personal Site
site_url: https://reahill.github.io
repo_url: https://github.com/reahill/reahill.github.io
theme:
  name: material
  palette:
    # 1. 自动模式入口 - 不定义具体颜色，仅提供切换入口
    - media: "(prefers-color-scheme)"  # 匹配系统是否有主题偏好
      toggle: 
        icon: material/brightness-auto  # 自动模式图标
        name: 切换到浅色模式  # 当处于自动模式时，按钮显示此文字

    # 2. 浅色模式的具体配色
    - media: "(prefers-color-scheme: light)"  # 匹配系统浅色模式
      scheme: default                  # 使用浅色基础方案
      primary: black                   # 主色调：黑色
      accent: blue               # 强调色：蓝色
      toggle:
        icon: material/weather-sunny    # 太阳图标
        name: 切换到深色模式           # 在浅色模式下，按钮提示切换至深色

    # 3. 深色模式的具体配色
    - media: "(prefers-color-scheme: dark)"
      scheme: slate                    # 使用深色基础方案
      primary: black             # 主色调：黑色
      accent: indigo                    # 深色模式下，强调色可微调为更亮的蓝色
      toggle:
        icon: material/weather-night    # 月亮图标
        name: 切换到系统自动模式       # 在深色模式下，按钮提示切换回自动
  font:
    text: Lora                # 设置正文字体
    code: "Cousine"               # 设置正文字体和代码字体
  language: zh                # 网站语言设置为中文
  icon:
    repo: fontawesome/brands/github  # 使用 FontAwesome 的 GitHub 图标
    logo: material/robot-confused-outline  # 网站 Logo 图标
    menu: material/menu  # 菜单图标
    close: material/close  # 关闭图标
    top: material/chevron-up  # 返回顶部图标
    previous: material/chevron-left  # 上一页图标
    next: material/chevron-right  # 下一页图标
  features:
    - navigation.instant     # 启用即时导航
    - navigation.instant.fetch  # 启用即时导航预取
    - navigation.instant.sections  # 启用即时导航分区
    - navigation.instant.progress  # 启用即时导航进度条
    - navigation.tracking  # 启用导航跟踪
    - navigation.sidebar  # 启用侧边栏导航
    - navigation.tabs # 启用标签导航
    - navigation.tabs.sticky  # 启用粘性标签导航
    - navigation.top        # 启用返回顶部按钮
    - navigation.sections    # 启用页面内导航分区
    - navigation.expand      # 启用导航展开
    - navigation.paths      # 启用导航路径
    - navigation.indexes  # 启用索引导航
    - navigation.prev_next  # 启用上一页/下一页导航
    - navigation.top # 启用返回顶部导航
    - search.highlight        # 启用搜索高亮
    - search.suggest          # 启用搜索建议
    - toc.integrate          # 启用集成目录
    - toc.follow            # 启用跟随目录
markdown_extensions:  
  - material.extensions.preview:  
      configurations:  
        - targets:
            include:  
              - changelog/index.md
              - customization.md  
              - insiders/changelog/*  
              - setup/extensions/*  
plugins:
  - search  
  - blog
nav:
  - 首页: index.md
  - 关于我: about.md
docs_dir: docs